import { Metadata } from 'next'
import React from 'react'
import AuthSession from '../HOC/AuthSession'
import { Session } from 'next-auth'
import NavgationControl from './NavgationControl'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface LayoutProps {
    children: React.ReactNode,
    session: Session
}

export default function Layout({ children, session }: LayoutProps) {
    return (
        <div className='w-full'>
            <AuthSession session={session}>
                <NavgationControl>
                    {children}
                </NavgationControl>
            </AuthSession>
        </div>
    )
}
