import { Metadata } from 'next'
import React from 'react'
import Nabvar from '../compontents/nabvar/Nabvar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div>
            <Nabvar />
            {children}
        </div>
    )
}
