import AdminNab from '@/app/compontents/nabvar/AdminNab'
import { Metadata } from 'next'
import React from 'react'




export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}



export default function Layout({ children, params
}: {
    children: React.ReactNode,
    params: { user: string }
}) {
    console.log('params:', params)
    return (
        <>
            <AdminNab />
            {children}
        </>
    )
}
